### ISSUE TITLE
Terminology paths in the CQL

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#16]
Several of the expressions in the CQL use explicit terminology paths rather than relying on the model info defaults. Are these intentional, or should they be removed to allow the model info to provide the terminology path for a resource?

**Comment by cmoesel** [comment]
Note that the FHIR 3.0.0 modelinfo seems to have some invalid `primaryCodePath` values.  For example, `MedicationRequest` indicates the primary code path as `medicationCodeableConcept`, but this property no longer exists since the introduction of the `ChoiceType` (which removed the `medicationCodeableConcept` property in favor of a `medication` choice type.  So... you'll probably have to fix the modelinfo.

**Comment by brynrhodes** [comment]
The use of explicit code paths removes potential ambiguity and makes it clear what path is being used. Additionally, eCQM development is leaning towards making all code paths explicit when using CQL with FHIR so that there is no question what code path is being used to select the data.
